<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Collapse side panel_fGpujc-scene-UzW_107d96</name>
   <tag></tag>
   <elementGuidId>6721deaf-b1d5-4398-a72f-6c13cfb5854c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;scene&quot;)/div[@class=&quot;fGpujc-scene widget-scene&quot;]/canvas[@class=&quot;fGpujc-scene-UzWXSb widget-scene-canvas&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>canvas.fGpujc-scene-UzWXSb.widget-scene-canvas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>f3bb4bf7-0032-459c-957e-19334233bd22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>2400</value>
      <webElementGuid>6bfeec3e-db52-4086-919e-62e275775b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1298</value>
      <webElementGuid>a5e12377-1d6d-48f5-bd0d-52252014aefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fGpujc-scene-UzWXSb widget-scene-canvas</value>
      <webElementGuid>ada4e27f-dff5-4cf3-919e-bfc0bd010860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>af631c39-7c64-4ed0-bb40-ca212e35be40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scene&quot;)/div[@class=&quot;fGpujc-scene widget-scene&quot;]/canvas[@class=&quot;fGpujc-scene-UzWXSb widget-scene-canvas&quot;]</value>
      <webElementGuid>4d7e9287-452e-4ede-9cf9-c1dca863a89f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='']</value>
      <webElementGuid>8d33be1b-95ef-4db9-baa6-82c1cdf8fe3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scene']/div[3]/canvas</value>
      <webElementGuid>7d06b906-f7d0-4285-8cd9-9cdcec6b96a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>c5db1879-8d7f-4b57-be92-45e5d4cfc336</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
