<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Whats here</name>
   <tag></tag>
   <elementGuidId>a45105c7-708f-4392-a455-224b684ae6a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Directions to here'])[1]/following::li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7392b419-9669-413c-82ff-8c04ce477961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7a0e8b89-d715-4133-8e49-0e57a1873a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>1447c58e-3a60-4add-9e05-8aad9e62daf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitemradio</value>
      <webElementGuid>9cd67733-a944-49fd-9166-6b712428a90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>be8f9afb-ef71-4d30-bc19-aee3a31c218f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ved</name>
      <type>Main</type>
      <value>1i:4,t:6894,e:3,p:x5pdYr-aL_GhseMP86WO4Ak:70</value>
      <webElementGuid>e86385bd-2426-4649-a550-fbe37ddf8198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vet</name>
      <type>Main</type>
      <value>6894</value>
      <webElementGuid>9db31b86-c4e5-4e87-8ea9-ec31e5aed2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>click: actionmenu.select; keydown: actionmenu.keydown;</value>
      <webElementGuid>9bbd4b67-1818-422e-906d-20bc09c1b066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jstcache</name>
      <type>Main</type>
      <value>316</value>
      <webElementGuid>a2693af0-7d1f-4b26-8a60-4d995ae1e7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsinstance</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>345e8f75-d833-4ce8-977d-a5c26cf5fa60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nbpPqf-menu-x3Eknd</value>
      <webElementGuid>1b3673ad-adff-42da-b90a-3a28d4f5cfce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsan</name>
      <type>Main</type>
      <value>0.aria-checked,7.nbpPqf-menu-x3Eknd,0.data-index,0.role,0.tabindex,0.ved,0.vet,0.jsaction</value>
      <webElementGuid>7bf4587a-b22f-40da-8c11-91fffe514970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>What's here?</value>
      <webElementGuid>eb95c7d4-89b1-4423-95c1-d1c6fb1fca7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;action-menu&quot;)/ul[1]/li[@class=&quot;nbpPqf-menu-x3Eknd&quot;]</value>
      <webElementGuid>1f65b7d6-bbea-4a98-a597-7016a0db558f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Directions to here'])[1]/following::li[1]</value>
      <webElementGuid>90192eb9-f616-4caf-9770-08f51643be02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Directions from here'])[1]/following::li[2]</value>
      <webElementGuid>90ce992c-fec4-4fb4-be2a-8a39c3ee0c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search nearby'])[1]/preceding::li[1]</value>
      <webElementGuid>3a3510a4-4fd3-4222-b02e-8e3c9f47e0ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='action-menu']/ul/li[4]</value>
      <webElementGuid>fb65f4e2-5ae7-4954-9421-ee3bbf946650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]</value>
      <webElementGuid>cc73fd7c-9e80-4691-88fe-a58466bb322b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
