<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Back to Online Calculator_fullframe</name>
   <tag></tag>
   <elementGuidId>038898fb-7e2a-477d-8fd6-694ef685e536</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fullframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fullframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>bf5ef720-3f48-43ce-abd4-291803ae17e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fullframe</value>
      <webElementGuid>87de161c-193d-49b4-9c0e-d2139fd1d4b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/html5/simple/index.php?v=10</value>
      <webElementGuid>8d45832c-c1d3-43ad-9f36-e106da3a18e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>63588e32-0240-4379-9967-9ddfc7ac37a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>b26f7de0-061d-45ff-890e-21f16ef4d250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>5b08adb1-a527-47e8-9e62-b2ce19192821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f5da3e13-e8f9-41cb-85ec-818c2ada90f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fullframe&quot;)</value>
      <webElementGuid>559cd3c2-d613-46aa-8d1c-e90fd8bd004f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fullframe']</value>
      <webElementGuid>fc29f9e0-fd28-4947-9896-b23ee657c0a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AppHolder']/iframe</value>
      <webElementGuid>6f32110b-f5ed-44d5-b143-4ccb72fa295b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>91eeba6a-a0b3-4b65-9d2f-4596c9f8cbb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
